jobs:
  include:
    - language: android
      os: linux
      dist: bionic
      android:
        components:
          - tools
          - platform-tools
          - build-tools-29.0.3
          - android-29
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      before_install:
        - openssl aes-256-cbc -K $encrypted_c670c9b85964_key -iv $encrypted_c670c9b85964_iv
          -in secrets.tar.gz.enc -out secrets.tar.gz -d
        - tar xf secrets.tar.gz
        - nvm install node
        - npm install -g yarn
        - yes | sdkmanager "build-tools;29.0.3"
      install:
        - gem install fastlane
        - yarn install
      before_script:
        - echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        - echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      script:
        - if [ -n "$TRAVIS_TAG" ]; then yarn android:beta; fi
        - if [ -z "$TRAVIS_TAG" ]; then yarn android:build; fi
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      before_deploy:
        - export APK_DIR="android/app/build/outputs/apk/release"
        - mv $APK_DIR/app-x86_64-release.apk $APK_DIR/learnX-x86_64-$TRAVIS_TAG.apk
        - mv $APK_DIR/app-arm64-v8a-release.apk $APK_DIR/learnX-arm64-v8a-$TRAVIS_TAG.apk
        - mv $APK_DIR/app-armeabi-v7a-release.apk $APK_DIR/learnX-armeabi-v7a-$TRAVIS_TAG.apk
        - mv $APK_DIR/app-x86-release.apk $APK_DIR/learnX-x86-$TRAVIS_TAG.apk
        - mv $APK_DIR/app-universal-release.apk $APK_DIR/learnX-universal-$TRAVIS_TAG.apk
      deploy:
        provider: releases
        edge: true
        token: $GITHUB_TOKEN
        file_glob: true
        file: android/app/build/outputs/apk/release/*.apk
        cleanup: false
        overwrite: true
        prerelease: true
        on:
          tags: true
    - language: objective-c
      os: osx
      osx_image: xcode11.4
      podfile: ios/Podfile
      cache:
        - yarn
        - cocoapods
      before_install:
        - openssl aes-256-cbc -K $encrypted_c670c9b85964_key -iv $encrypted_c670c9b85964_iv
          -in secrets.tar.gz.enc -out secrets.tar.gz -d
        - tar xf secrets.tar.gz
        - sed -i'.bak' -e "s/GITHUB_TOKEN/$GITHUB_TOKEN/" fastlane/Matchfile
        - nvm install node
        - npm install -g yarn
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - gem install fastlane
        - gem install cocoapods
        - yarn install
        - cd ios && pod install && cd ..
      script:
        - if [ -n "$TRAVIS_TAG" ]; then yarn ios:beta; fi
        - if [ -z "$TRAVIS_TAG" ]; then yarn ios:test:release; fi
